[project]
name = "yourbench"
version = "0.2.0"
description = "Dynamic Evaluation Set Generation with Large Language Models"
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
    "gradio>=5.16.0",
]


[tool.setuptools.packages.find]
where = ["yourbench"]
