[project]
name = "yourbench"
version = "0.2.0"
description = "Dynamic Evaluation Set Generation with Large Language Models"
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
    "gradio>=5.16.0",
    "hf-transfer>=0.1.9",
    "loguru>=0.7.3",
    "markitdown>=0.0.1a4",
    "openai>=1.63.0",
    "python-dotenv>=1.0.1",
]

[project.scripts]
yourbench = "yourbench.main:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["yourbench*"]
